UPDATE TB_SUBWAY_STATN
      SET STATN_NM = '开伙开'
 WHERE STATN_NM = '开伙'
 ;
 
 SELECT SUBWAY_STATN_NO
    , LN_NM
    , STATN_NM
FROM TB_SUBWAY_STATN
WHERE STATN_NM = '开伙开'
;

COMMIT;

UPDATE TB_SUBWAY_STATN
SET STATN_NM = '开伙'
WHERE STATN_NM = '开伙开'
;

COMMIT;

UPDATE TB_SUBWAY_STATN
SET STATN_NM = '开伙开'
WHERE STATN_NM = '开伙'
;

ROLLBACK;

 SELECT SUBWAY_STATN_NO
    , LN_NM
    , STATN_NM
FROM TB_SUBWAY_STATN
WHERE STATN_NM = '开伙'
;

SAVEPOINT SVPT1;

UPDATE TB_SUBWAY_STATN
SET STATN_NM = '开伙开'
WHERE STATN_NM = '开伙'
;

SAVEPOINT SVPT2;

UPDATE TB_SUBWAY_STATN
SET STATN_NM = '碍巢开'
WHERE STATN_NM = '碍巢'
;

SAVEPOINT SVPT3;

UPDATE TB_SUBWAY_STATN
SET STATN_NM = '规硅开'
WHERE STATN_NM = '规硅'
;

SELECT A.SUBWAY_STATN_NO, A.LN_NM, A.STATN_NM
FROM TB_SUBWAY_STATN A
WHERE A.STATN_NM IN ('开伙', '开伙开', '碍巢', '碍巢开', '规硅', '规硅开')
;

ROLLBACK TO SVPT3;

SELECT A.SUBWAY_STATN_NO, A.LN_NM, A.STATN_NM
FROM TB_SUBWAY_STATN A
WHERE A.STATN_NM IN ('开伙', '开伙开', '碍巢', '碍巢开', '规硅', '规硅开')
;

ROLLBACK TO SVPT2;

SELECT A.SUBWAY_STATN_NO, A.LN_NM, A.STATN_NM
FROM TB_SUBWAY_STATN A
WHERE A.STATN_NM IN ('开伙', '开伙开', '碍巢', '碍巢开', '规硅', '规硅开')
;

ROLLBACK TO SVPT1;

SELECT A.SUBWAY_STATN_NO, A.LN_NM, A.STATN_NM
FROM TB_SUBWAY_STATN A
WHERE A.STATN_NM IN ('开伙', '开伙开', '碍巢', '碍巢开', '规硅', '规硅开')
;