SELECT A.INDUTY_CL_CD
        , A.INDUTY_CL_NM
        , A.INDUTY_CL_SE_CD
        , A.UPPER_INDUTY_CL_CD
FROM TB_INDUTY_CL A
;

SELECT A.INDUTY_CL_CD
        , A.INDUTY_CL_NM
        , A.INDUTY_CL_SE_CD
        , A.UPPER_INDUTY_CL_CD
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_NM LIKE '%Ŀ��%'
;

SELECT A.SUBWAY_STATN_NO, A.LN_NM, A.STATN_NM
FROM TB_SUBWAY_STATN A
WHERE A.STATN_NM = '���￪'
;

SELECT A.SUBWAY_STATN_NO
    , A.STD_YM
    , A.BEGIN_TIME
    , A.END_TIME
    , A.TK_GFF_SE_CD
    , A.TK_GFF_CNT
FROM TB_SUBWAY_STATN_TK_GFF A
WHERE A.SUBWAY_STATN_NO = '000032'
    AND A.STD_YM = '202010'
    AND A.BEGIN_TIME LIKE '18%'
    AND A.END_TIME LIKE '19%'
    AND A.TK_GFF_SE_CD IN ('TGS001', 'TGS002')
;

SELECT A.ADRES_CL_CD
    , A.ADRES_CL_NM
    , A.ADRES_CL_SE_CD
    , NVL(A.UPPER_ADRES_CL_CD, '(Null)') UPPER_ADRES_CL_CD
FROM TB_ADRES_CL A
WHERE A.UPPER_ADRES_CL_CD IS NULL
;

SELECT A.ADRES_CL_CD
    , A.ADRES_CL_NM
    , A.ADRES_CL_SE_CD
    , NVL(A.UPPER_ADRES_CL_CD, '(Null)') UPPER_ADRES_CL_CD
FROM TB_ADRES_CL A
WHERE A.UPPER_ADRES_CL_CD IS NOT NULL
;

SELECT A.BSSH_NO
    , A.CMPNM_NM
    , A.LNM_ADRES
FROM TB_BSSH A
WHERE A.LNM_ADRES LIKE '����%'
    AND (
                A.CMPNM_NM LIKE '%��Ÿ����%'
            OR A.CMPNM_NM LIKE '%�̵��%'
            OR A.CMPNM_NM LIKE '%�Ľ�����%'
            )
    AND NOT A.LNM_ADRES LIKE '%������%'
;

-- �ȵ�, REGEXP_LIKE�� ����ؾ���.

SELECT A.BSSH_NO
    , A.CMPNM_NM
    , A.LNM_ADRES
FROM TB_BSSH A
WHERE A.LNM_ADRES LIKE '����%'
    AND A.CMPNM_NM LIKE IN ('%��Ÿ����%', '%�̵��%', '%�Ľ�����%')
    AND NOT A.LNM_ADRES LIKE '%������%'
;

SELECT A.SUBWAY_STATN_NO
    , A.STD_YM
    , A.BEGIN_TIME
    , A.END_TIME
    , CASE 
        WHEN A.TK_GFF_SE_CD = 'TGS001' THEN '����'
        WHEN A.TK_GFF_SE_CD = 'TGS002' THEN '����'
    END AS ����������
    , A.TK_GFF_CNT
FROM TB_SUBWAY_STATN_TK_GFF A
WHERE A.SUBWAY_STATN_NO = '000032'
    AND A.STD_YM = '202010'
    AND A.TK_GFF_SE_CD IN ('TGS001', 'TGS002')
    AND NOT A.TK_GFF_CNT < 100000
;

SELECT A.SUBWAY_STATN_NO
    , A.STD_YM
    , A.BEGIN_TIME
    , A.END_TIME
    , CASE
        WHEN A.TK_GFF_SE_CD = 'TGS001' THEN '����'
        WHEN A.TK_GFF_SE_CD = 'TGS002' THEN '����'
    END AS ����������
    , A.TK_GFF_CNT
FROM TB_SUBWAY_STATN_TK_GFF A
WHERE A.SUBWAY_STATN_NO = '000032'
    AND A.STD_YM = '202010'
    AND A.TK_GFF_SE_CD NOT IN ('TGS001')
    AND A.TK_GFF_CNT NOT BETWEEN 0 AND 99999
;

CREATE TABLE TB_CHAR
(
    CHAR_NO CHAR(4)
    ,   CHAR_4 CHAR(4)
    , CHAR_5 CHAR(5)
    , CONSTRAINT PK_TB_CHAR PRIMARY KEY (CHAR_NO)
)
;

INSERT INTO TB_CHAR (CHAR_NO, CHAR_4, CHAR_5)
    VALUES ('1001', 'SQLD', 'SQLD');
    
INSERT INTO TB_CHAR (CHAR_NO, CHAR_4, CHAR_5)
    VALUES ('1002', 'SQLD', 'SQLP');
    
COMMIT;

SELECT REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(CHAR_5, ' ', '_') AS CHAR_5
FROM TB_CHAR
;

SELECT CHAR_NO
    , REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(CHAR_5, ' ', '_') AS CHAR_5
FROM TB_CHAR
WHERE CHAR_4 = 'SQLD'
    AND CHAR_4 = CHAR_5
;

INSERT INTO TB_CHAR (CHAR_NO, CHAR_4, CHAR_5)
    VALUES ('1003', 'SQ D', 'SQ D');
    
COMMIT;   

-- 공백만 다르면 같다고 판단하네

SELECT CHAR_NO
    , REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(CHAR_5, ' ', '_') AS CHAR_5
FROM TB_CHAR
WHERE CHAR_4 = 'SQ D'
    AND CHAR_4 = CHAR_5
;

SELECT CHAR_NO
    , REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(CHAR_5, ' ', '_') AS CHAR_5
FROM TB_CHAR
WHERE CHAR_NO = '1002'
    AND CHAR_4 < CHAR_5
;

CREATE TABLE TB_VARCHAR2
(
    VARCHAR_NO CHAR(4)
    , CHAR_4 CHAR(4)
    , VARCHAR2_NO VARCHAR2(5)
    , CONSTRAINT PK_TB_VARCHAR2 PRIMARY KEY (VARCHAR_NO)
)
;

INSERT INTO TB_VARCHAR2(VARCHAR_NO, CHAR_4, VARCHAR2_NO) VALUES ('1001', 'SQLD', 'SQLD ');
INSERT INTO TB_VARCHAR2(VARCHAR_NO, CHAR_4, VARCHAR2_NO) VALUES ('1002', 'SQLD', 'SQLP ');
COMMIT;

SELECT REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(VARCHAR2_NO, ' ', '_') AS VARCHAR_5
FROM TB_VARCHAR2
;

SELECT REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(VARCHAR2_NO, ' ', '_') AS VARCHAR2_NO
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
    AND CHAR_4 = VARCHAR2_NO
;    

SELECT REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(VARCHAR2_NO, ' ', '_') AS VARCHAR2_5
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
    AND CHAR_4 = TRIM(VARCHAR2_NO)
;

SELECT REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(VARCHAR2_NO, ' ', '_') AS VARCHAR2_NO
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
    AND CHAR_4 = 'SQLD '
;

SELECT REPLACE(CHAR_4, ' ', '_') AS CHAR_4
    , REPLACE(VARCHAR2_NO, ' ', '_') AS VARCHAR2_NO
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
    AND VARCHAR2_NO = 'SQLD'
;    

SELECT ROWNUM AS RNUM
    , A.BSSH_NO
    , A.CMPNM_NM
    , NVL(A.BHF_NM, '(Null)') AS BHF_NM
    , A.LNM_ADRES
FROM TB_BSSH A
WHERE ROWNUM <= 10
;

