CREATE TABLE TB_RN_TMP
(
    RN_CD VARCHAR2(12) NOT NULL
    , RN VARCHAR2(150) NOT NULL
);

CREATE TABLE TB_SUBWAY_STATIN_TMP
(
    SUBWAY_STATN_NO CHAR(6) NOT NULL
    , LN_NM VARCHAR2(50) NOT NULL
    , STATN_NM VARCHAR2(50) NOT NULL
    , CONSTRAINT PK_TB_SUBWAY_STATN_TMP PRIMARY KEY(SUBWAY_STATN_NO)
);

CREATE TABLE TB_SUBWAY_STATN_TK_GFF_TMP
(
    SUBWAY_STATN_NO CHAR(6) NOT NULL
    , STD_YM CHAR(6) NOT NULL
    , BEGIN_TIME CHAR(4) NOT NULL
    , END_TIME CHAR(4) NOT NULL
    , TK_GFF_SE_CD VARCHAR(6) NOT NULL
    , TK_GFF_CNT NUMBER(15) NOT NULL
    , CONSTRAINT PK_TB_SUBWAY_STATN_TK_GFF_TMP PRIMARY KEY
    (SUBWAY_STATN_NO, STD_YM, BEGIN_TIME, END_TIME, TK_GFF_SE_CD)
);

ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP
ADD CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1
FOREIGN KEY (SUBWAY_STATN_NO)
REFERENCES TB_SUBWAY_STATIN_TMP (SUBWAY_STATN_NO);

ALTER TABLE TB_SUBWAY_STATIN_TMP ADD (OPEN_YN CHAR(1));

ALTER TABLE TB_SUBWAY_STATIN_TMP DROP COLUMN OPEN_YN;

ALTER TABLE TB_SUBWAY_STATIN_TMP ADD(OPER_YN CHAR(1) NULL);

ALTER TABLE TB_SUBWAY_STATIN_TMP MODIFY (OPER_YN NUMBER(1)
                                                                DEFAULT 0 NOT NULL
                                                                NOVALIDATE);
                                                                
ALTER TABLE TB_SUBWAY_STATIN_TMP
RENAME COLUMN OPER_YN TO OPERATION_YN;

ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP
DROP CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1;

ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP
ADD CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1
FOREIGN KEY (SUBWAY_STATN_NO)
REFERENCES TB_SUBWAY_STATIN_TMP (SUBWAY_STATN_NO);

RENAME TB_SUBWAY_STATN_TK_GFF_TMP TO TB_SUBWAY_STATN_TK_GFF_TMP_2;

SELECT A.TABLE_NAME
     , A.CONSTRAINT_NAME
     , B.COLUMN_NAME     
     , B.POSITION
  FROM ALL_CONSTRAINTS  A
     , ALL_CONS_COLUMNS B
 WHERE A.TABLE_NAME      = 'TB_SUBWAY_STATN_TK_GFF_TMP_2'
--   AND A.CONSTRAINT_TYPE = 'P' 

   AND A.OWNER           = B.OWNER
   AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
 ORDER BY B.POSITION;
 
 DESC TB_SUBWAY_STATN_TK_GFF_TMP_2;
 
TRUNCATE TABLE TB_SUBWAY_STATN_TK_GFF_TMP_2;

DROP TABLE TB_SUBWAY_STATN_TK_GFF_TMP_2;
DROP TABLE TB_SUBWAY_STATIN_TMP;
DROP TABLE TB_RN_TMP;

