CREATE TABLE TB_SUBWAY_STATN_TMP
(
    SUBWAY_STATN_NO CHAR(6) NOT NULL
,   LN_NM VARCHAR2(50) NOT NULL
,   STATN_NM VARCHAR2(50) NOT NULL
, CONSTRAINT PK_TB_SUBWAY_STATN_TMP PRIMARY KEY (SUBWAY_STATN_NO)
);

INSERT INTO TB_SUBWAY_STATN_TMP T
(
    T.SUBWAY_STATN_NO
,   T.LN_NM
,   T.STATN_NM
)
VALUES
(
    '000032'
,   '2호선'
,   '강남'
)
;

COMMIT;

SELECT A.SUBWAY_STATN_NO
         , A.LN_NM
         , A.STATN_NM
 FROM TB_SUBWAY_STATN_TMP A
WHERE A.STATN_NM = '강남'
;

UPDATE TB_SUBWAY_STATN_TMP A
    SET A.LN_NM = '녹색선'
    ,   A.STATN_NM = '강남스타일'
WHERE A.SUBWAY_STATN_NO = '000032'
;

COMMIT;

DELETE
FROM TB_SUBWAY_STATN_TMP A
WHERE A.SUBWAY_STATN_NO = '000032'
;

COMMIT;

SELECT A.SUBWAY_STATN_NO
         , A.LN_NM
         , A.STATN_NM
 FROM TB_SUBWAY_STATN_TMP A
WHERE A.SUBWAY_STATN_NO = '000032'
;

SELECT A.INDUTY_CL_CD
,   A.INDUTY_CL_NM
,   A.INDUTY_CL_SE_CD
,   NVL(A.UPPER_INDUTY_CL_CD, '(Null)') AS UPPER_INDUTY_CL_CD
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_SE_CD = 'ICS001'
;

SELECT DISTINCT A.INDUTY_CL_SE_CD
FROM TB_INDUTY_CL A
;

SELECT DISTINCT A.POPLTN_SE_CD, A.AGRDE_SE_CD
FROM TB_POPLTN A
;

SELECT *
FROM TB_INDUTY_CL_SE A
;

SELECT A.INDUTY_CL_CD AS 업종분류코드
,   A.INDUTY_CL_NM AS 업종분류명
,   A.INDUTY_CL_SE_CD AS 업종분류구분코드
,   NVL(A.UPPER_INDUTY_CL_CD, '(Null)') AS 상위업종분류코드
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_SE_CD = 'ICS001'
;

SELECT SUBWAY_STATN_NO || '-' || STATN_NM || '(' || LN_NM || ')' AS "지하철역번호-역명(노선명)"
FROM TB_SUBWAY_STATN
WHERE LN_NM = '9호선'
;

SELECT ((1+1)*3) / 6 AS "연산결과 값"
FROM DUAL
;

