--코드 5-86 2개의 테이블 조인
SELECT A.SUBWAY_STATN_NO
     , A.LN_NM
     , A.STATN_NM
     , B.BEGIN_TIME
     , B.END_TIME
     , CASE WHEN TK_GFF_SE_CD = 'TGS001' THEN '승차'
            WHEN TK_GFF_SE_CD = 'TGS002' THEN '하차'
            END TK_GFF_SE_NM
     , B.TK_GFF_CNT
  FROM TB_SUBWAY_STATN A
     , TB_SUBWAY_STATN_TK_GFF B
 WHERE A.SUBWAY_STATN_NO = B.SUBWAY_STATN_NO
   AND A.SUBWAY_STATN_NO = '000032' --2호선 강남
   AND B.STD_YM = '202010'
   AND B.BEGIN_TIME = '0800'
   AND B.END_TIME = '0900'
 ;

--코드 5-87 3개의 테이블 조인
SELECT A.SUBWAY_STATN_NO
     , A.LN_NM
     , A.STATN_NM
     , B.BEGIN_TIME
     , B.END_TIME
     , C.TK_GFF_SE_NM
     , B.TK_GFF_CNT
  FROM TB_SUBWAY_STATN A
     , TB_SUBWAY_STATN_TK_GFF B
     , TB_TK_GFF_SE C
 WHERE A.SUBWAY_STATN_NO = B.SUBWAY_STATN_NO
  AND A.SUBWAY_STATN_NO = '000032' --2호선 강남
  AND B.STD_YM = '202010'
  AND B.BEGIN_TIME = '0800'
  AND B.END_TIME = '0900'
  AND B.TK_GFF_SE_CD = C.TK_GFF_SE_CD
;

--코드 5-88 4개의 테이블 조인
SELECT A.ADSTRD_CD
     , D.ADSTRD_NM
     , A.POPLTN_SE_CD
     , B.POPLTN_SE_NM
     , A.AGRDE_SE_CD
     , C.AGRDE_SE_NM
     , A.POPLTN_CNT
  FROM TB_POPLTN A
     , TB_POPLTN_SE B
     , TB_AGRDE_SE C
     , TB_ADSTRD D
 WHERE A.ADSTRD_CD = D.ADSTRD_CD
   AND A.POPLTN_SE_CD = B.POPLTN_SE_CD
   AND A.AGRDE_SE_CD = C.AGRDE_SE_CD
   AND A.POPLTN_SE_CD IN ( 'M', 'F')
   AND A.STD_YM = '202010'
   AND C.AGRDE_SE_CD IN ('020', '030', '040')
   AND D.ADSTRD_NM LIKE '%경기도%고양시%덕양구%삼송%'
ORDER BY A.POPLTN_CNT DESC
;