--코드 2-1 사용자 계정 생성 - SYSTEM 계정으로 로그인하여 실행
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER SQLD IDENTIFIED BY 1234; --사용자 계정 생성
ALTER USER SQLD ACCOUNT UNLOCK; --생성한 사용자 계정의 잠금 해제
GRANT RESOURCE, DBA, CONNECT TO SQLD; --생성한 사용자 계정에게 권한 부여

--코드 2-2 테이블 스페이스 및 임시 테이블 스페이스 생성 - SYSTEM 계정으로 로그인하여 실행
CREATE TABLESPACE SQLD_DATA
DATAFILE 'C:\app\mildsalmon\product\18.0.0\oradata\XE\SQLD_DATA.dbf' SIZE 4G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE SQLD_TEMP
TEMPFILE 'C:\app\mildsalmon\product\18.0.0\oradata\XE\SQLD_TEMP.dbf' SIZE 1G
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--코드 2-3 디폴트 및 임시 테이블 스페이스 지정 - SYSTEM 계정으로 로그인하여 실행
ALTER USER SQLD DEFAULT TABLESPACE SQLD_DATA;
ALTER USER SQLD TEMPORARY TABLESPACE SQLD_TEMP;

